# Generated by Django 4.1.3 on 2022-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potential_app', '0002_userbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='user_id',
            new_name='user',
        ),
    ]
